### ISSUE TITLE
model license?

### ISSUE THREAD

**Issue by go-to-here** [VinAIResearch/blur-kernel-space-exploring#6]
Hello! Thank you so much for sharing the code and the model.

I would like to ask, what protocol is the pre-training model? Can I use it in a business project?

Your reply is very much needed.

**Comment by P0lyFish** [comment]
Thank you for your interest.

Our code is based on other projects (Please check the references in README.md) and the pre-trained models are trained using REDS and GOPRO datasets, other than that, everything is free to use according to Apache-2.0 License. But keep in mind that we have no responsibility for any issue caused by the code.
